"""create cv_feedback table

Revision ID: 37f61e7738ee
Revises: dea6527a9116
Create Date: 2026-03-05 15:59:58.966582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f61e7738ee'
down_revision: Union[str, Sequence[str], None] = 'dea6527a9116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_link', sa.String(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_feedbacks_id'), 'cv_feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_feedbacks_id'), table_name='cv_feedbacks')
    op.drop_table('cv_feedbacks')
    # ### end Alembic commands ###
